---
name: godeb
description: simple debian packaging for go service
author: Mario Finelli
inputs:
  cc:
    default: ""
    description: Override the "CC" environment variable during build
    required: false
  goarch:
    default: ""
    description: Override the "GOARCH" environment variable during build
    required: false
  include-source:
    default: false
    description: Pass "--source" to build.bash for a source-included build
    required: false
  signing-key:
    default: ""
    description: GPG key ID to use for package signing
    required: false
  update-changelog:
    default: false
    description: Run the changelog.bash script to update the debian/changelog
    required: false
runs:
  using: "composite"
  steps:
    # - run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    #   shell: bash
    #   env:
    #     GITHUB_ACTION_PATH: ${{ github.action_path }}

    - run: >-
        ${{ github.action_path }}/changelog.bash
        "$(grep UBUNTU_CODENAME /etc/os-release | awk -F= '{print $2}')"
      if: inputs.update-changelog == true
      shell: bash

    - run: ${{ github.action_path }}/build.bash
      if: inputs.include-source == false
      shell: bash
      env:
        CC: ${{ inputs.cc }}
        GOARCH: ${{ inputs.goarch }}

    - run: ${{ github.action_path }}/build.bash --source
      if: inputs.include-source == true
      shell: bash
      env:
        CC: ${{ inputs.cc }}
        GOARCH: ${{ inputs.goarch }}

    - run: >-
        debsigs --sign=origin -k ${{ inputs.signing-key }}
        $(yq e '.project' < godeb.yaml)_*.deb
      if: inputs.signing-key != ''
      shell: bash
