---
name: Default
on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck *.bash
      - run: sudo apt-get update
      - run: sudo apt-get install -y bats
      - run: bats test/changelog.bats
